name: Create a release commit and publish new tag
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Test
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}    

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.x  

      - name: Standard Version Release
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: git config --global user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
      - run: git config --global user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
      - run: yarn release
        env:
          CI: false
      - run: git push --follow-tag
